### ISSUE TITLE
Page navigation (next/previous) in custom footer

### ISSUE THREAD

**Issue by stockbal** [1DSAG/ADT-Leitfaden#10]
To improve navigation between the chapters we could introduce links that allow navigating to the next or previous chapter at the end of the page.

![image](https://user-images.githubusercontent.com/35834861/224538736-64af66cc-986d-4b31-a9b5-5cbbd40115a0.png)  
<span style="font-size: 0.8em"><em>Screenshot: Front Matter in specific page</em></span>

![image](https://user-images.githubusercontent.com/35834861/224538805-8a6c8f3b-313f-4650-9c9f-682ed364d790.png)  
<span style="font-size: 0.8em"><em>Screenshot: Custom Footer in "_includes" folder</em></span>

The final result would look like this:
![image](https://user-images.githubusercontent.com/35834861/224539104-6dff7817-bf91-457f-98d8-07a0ac0100fa.png)  
<span style="font-size: 0.8em"><em>Screeshot: Navigation Links in rendered footer</em></span>

**Comment by marianfoo** [comment]
I think this is a good addition.
But for this, the other chapters, just like the "Plug-In" chapter, would have to be divided into subchapters.

**Comment by stockbal** [comment]
Yes, for sure. Otherwise the benefit is not that great, especially for the big chapters. 😊
