### ISSUE TITLE
[Frage]: Nutzung von GitHub Discussion

### ISSUE THREAD

**Issue by lechnerc77** [1DSAG/ADT-Leitfaden#23]
Aktuell ist im Repository das Feature der [GitHub Discussions](https://github.com/features/discussions) nicht aktiviert. DIes würde den Austausch zu den Themen des Leitfadens vereinfachen (alles an einem Platz, Issues aus Diskussionen öffnen etc.).

Wurde dies bewusst von den Maintainern nicht aktiviert?

**Comment by marianfoo** [comment]
Habe jetzt noch nicht den Bedarf gesehen da bei anderen Projekten die wenig bis gar nicht genutzt wird.
Die Diskussion die es gibt sollten auch in Issues passen.
Bei UI5 Guide war das auch geplant, aber Diskussion waren da entweder in Issues, PRs oder offline.

**Comment by Xexer** [comment]
Diskussionen dann bitte einfach per Issue im Repo.
