### ISSUE TITLE
Besserer Begriff statt "Grundproblem"

### ISSUE THREAD

**Issue by BeckerWdf** [1DSAG/ADT-Leitfaden#36]
Im CDS-Kapitel steht folgender Satz:

> Ein Grundproblem bei den Core Data Services ist, dass die Eigenschaften eines Objektes (z. B. einer CDS View Entity) aus mehreren Dateien und den Eigenschaften der Datenquellen zusammengesetzt sind. 

Das Wort Grundproblem finde ich so negativ belegt. Können wir eine schöneren Begriff dafür finden?

**Comment by ABAP-Pete25** [comment]
Ein Versuch mittels kleiner Umformulierung das Wort "Grundproblem" zu entfernen mit PR #37

**Comment by BeckerWdf** [comment]
> Ein Versuch mittels kleiner Umformulierung das Wort "Grundproblem" zu entfernen mit PR #37

Gefällt mir
