### ISSUE TITLE
Benutzung der "Source Type" Facette im Project Explorer for Data Definitions

### ISSUE THREAD

**Issue by BeckerWdf** [1DSAG/ADT-Leitfaden#38]
In https://github.com/1DSAG/ADT-Leitfaden/blob/main/docs/working-with-adt/features/cds.md?plain=1#L25
werden die unterschiedlichen Entitätstypen angesprochen, die sich in einer "Data Definition" (in einem DDLS file) "verstecken" können. Seit ADT client version 3.32  in Verbindung mit den Back-end Versionen "SAP BTP ABAP environment 2302" bzw "SAP S/4HANA Cloud ABAP Environment 2302" oder neuer wird das in ADT transparenter dargestellt. 

Man kann des Entitäts-Typ:
1. Im "Properties" view sehen
2. Beim Suchen (z.B. im "Open ABAP Development Object" Dialog) als Suchkriterium mitgeben
3. Im "Project Explorer" den "Data Definitions" Knoten ad-hoc nach "Source Type" expandieren
4. Im "Project Explorer" eigene "Repository Trees" mit Hilfe der "Source Type" Facette definieren.

Siehe hierzu: 
https://help.sap.com/docs/SAP_S4HANA_CLOUD/53b14a3c9f7d4837a9c1f271ee3b24a4/193d4583c30f40a0a562dc200e0b0c41.html?locale=en-US#loio193d4583c30f40a0a562dc200e0b0c41__section_sourcetype_ddls

Auf diese hilfreiche Funktion könnte man in diesem Dokument doch auch hinweisen.

**Comment by BeckerWdf** [comment]
Soll ich eine PR zu diesem Thema machen?

**Comment by Xexer** [comment]
PRs sind immer gern gesehen. Entschuldige die späte Rückmeldung dazu, bisher fehlte leider die Zeit sich noch einmal die Fehler anzusehen.

**Comment by BeckerWdf** [comment]
> PRs sind immer gern gesehen. Entschuldige die späte Rückmeldung dazu, bisher fehlte leider die Zeit sich noch einmal die Fehler anzusehen.

Done

**Comment by Xexer** [comment]
Änderungen wurden in aktuelle Version übernommen
