### ISSUE TITLE
ABAP Cleaner (Marketing)

### ISSUE THREAD

**Issue by Xexer** [1DSAG/ADT-Leitfaden#42]
After the release of the ABAP cleaner, wo should document the new plugin and put it in the section for the motivation (https://github.com/SAP/abap-cleaner).

**Comment by se38** [comment]
Good idea (especialy because ABAP Cleaner is already my favorite, most used Plugin). 
The plugin should be documented in chapter "[Nützliche Open Source ADT Plugins](https://github.com/1DSAG/ADT-Leitfaden/blob/main/docs/plug-ins/open-source-adt-plugins.md)"

**Comment by ABAP-Pete25** [comment]
I also started to use it and I love it. I will start to write something about it. As soon I have some raw-writing I will inform here that maybe some will have a look on it. But I think it is a must to have it in our guide asap.
